### PR TITLE
Add Ali to About Page

### PR DESCRIPTION
**Pull request by mekkim**
Add Ali to About Page

### CODE REVIEW

**Comment by mekkim** [comment]
Some magic needs to be done to switch the LinkedIn icon for the IG icon.  I can't quite figure it out.  It's something to do with props and CSS and the profile.js component.

**Comment by humphd** [comment]
I'll look at this later tonight

**Comment by humphd** [comment]
I've made some fixes and pushed to this branch/PR.  See if you're happy with it.

Here is how it looks:

Screen Shot 2022-07-04 at 8 28 39 PM

**Comment by mekkim** [comment]
Looks great! Thanks for solving that and cleaning things up while you were at it.  Interestingly, that `<profile>` indent is a mystery to me as it doesn't show up in my editor (I check this time!) but seems to show up after commit.

**Pull request merged**
