### PR TITLE
Request form update

### PR DESCRIPTION
**Pull request by mekkim**
Creates address elements separately in addition to full address string for export to Canada Post software.
Changes order of mask size requests to put regular first
Adds school/work usage information
Adds mask sizing image

### CODE REVIEW

**Comment by mekkim** [comment]
Fixes #178 #167 #165

**Comment by mekkim** [comment]
I'm not quite sure I did the school & work demographic push quite right.  Also not sure about the address backend stuff.  The frontend on both is fine but I'm not sure I go the backend pushes right.

**Review by humphd — COMMENTED** [review]
I've taken a look at this, and made some fixes for you.  I don't have time to update the backend tests or report, but I'll file an issue to do it later.  See if you're OK with this.

NOTE: this requires updating front-end and back-end.

Also, due to time limitations, I haven't tested the full flow (i.e., test it yourself to see that it all works).

**Comment by humphd** [comment]
Filed #180 and #181 for follow-up later.

**Comment by humphd** [comment]
This is breaking the integration tests, I filed https://github.com/EBSECan/donatemask/issues/184 with the details and potential fix.

**Comment by mekkim** [comment]
I've broken something in the request form but can't figure out what it is.  It doesn't work on my local test server because I can't seem to map the api correctly for the local server.  I'm a bit out of my depth here.

**Comment by mekkim** [comment]
It's failing all the request form submit tests with a general catch of the error could not submit form.

**Comment by humphd** [comment]
@mekkim I'll look into it in the next few days if no one does before me.

**Comment by mekkim** [comment]
Thanks @humphd.  I know you're very busy this time of year.

**Pull request merged**
