### PR TITLE
Update donate form to fix autocomplete, label, and set default tier to 50

### PR DESCRIPTION
**Pull request by humphd**
When I refactored the Donate Form before, I missed a few things:

- use `autocomplete` attribute for `name` and `email` fields, so browser helps when filling
- fix accessibility of label for custom mask amount (copy/paste error)

I've also bumped the default tier to 50 from 25, based on previous outreach data.

### CODE REVIEW

**Review by mekkim — APPROVED** [review]
LGTM!

**Comment by mekkim** [comment]
And I waited for the checks to pass this time too! ;)

**Comment by humphd** [comment]
Before you release it live, let the integration one as well

**Comment by humphd** [comment]
Specifically: https://github.com/EBSECan/donatemask/actions/runs/2405731163

**Comment by mekkim** [comment]
D'oh! I jumped the gun again!  /me hits refresh on integration tests impatiently. ^_^

**Comment by humphd** [comment]
All good, ship it!

**Comment by mekkim** [comment]
Watching the tests happen in real time was actually super interesting.

**Comment by mekkim** [comment]
Live! (And /prod rebased to /main).

**Pull request merged**
